# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: Felipe Pfeifer Rubin
# Contact: felipe.rubin@acad.pucrs.br
# About: A Vagrant file for OS Labs - PUCRS 2018/2
# Following the configuration as specified: http://www.inf.pucrs.br/~emoreno/
#

# Buildroot version to use
RELEASE = '2017.11.2'
# Machine Power, change as required
VM_MEMORY = 4096
VM_CORES = 2
# The folder in your workstation you wish to share with the Vagrant VM

SHARED_FOLDER = File.dirname(__FILE__)+"/../sharedfolder/"
Vagrant.configure("2") do |config|

	config.vm.box = 'bento/ubuntu-16.04'

	config.vm.provider :vmware_fusion do |v, override|
		v.vmx['memsize'] = VM_MEMORY
		v.vmx['numvcpus'] = VM_CORES
	end

	config.vm.provider :virtualbox do |v, override|
		v.memory = VM_MEMORY
		v.cpus = VM_CORES

		required_plugins = %w( vagrant-vbguest )
		required_plugins.each do |plugin|
		  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
		end
		#Required to allow symlinks
		v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
	end


	config.vm.provider :parallels do |v, override|
		override.vm.box = "parallels/ubuntu-16.04"
		v.memory = VM_MEMORY
		v.cpus = VM_CORES  
		
		# v.check_guest_tools = true
		# v.update_guest_tools = true

		required_plugins = %w( vagrant-parallels )
		required_plugins.each do |plugin|
			system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
		end
		#v.update_guest_tools = true #Uncomment if you want to update parallels tools
	end

	config.vm.provision 'shell' do |s|
		s.inline = 'echo Setting up machine name'

		config.vm.provider :vmware_fusion do |v, override|
			v.vmx['displayname'] = "Buildroot #{RELEASE}"
		end

		config.vm.provider :virtualbox do |v, override|
			v.name = "Buildroot #{RELEASE}"
		end
		config.vm.provider :parallels do |v, override|
			v.name = "Buildroot #{RELEASE}"
		end
	end

	# config.vm.synced_folder "#{SHARED_FOLDER}",'/home/vagrant/linuxdistro'
	# config.vm.synced_folder "#{SHARED_FOLDER}","/home/vagrant/linuxdistro",type: "rsync"
	# config.vm.synced_folder "#{SHARED_FOLDER}",'/home/vagrant/linuxdistro', type: "smb", mount_options: ["sec=ntlm,vers=3.0,mfsymlink"]
	# config.vm.synced_folder  "#{SHARED_FOLDER}",'/home/vagrant/linuxdistro',owner:"vagrant",group:"vagrant", mount_options: ['share','nosuid']
	# config.vm.synced_folder "#{SHARED_FOLDER}","/home/vagrant/linuxdistro",type: "nfs",  linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
	# config.vm.synced_folder "#{SHARED_FOLDER}","/home/vagrant/linuxdistro",type: "nfs", mount_options: ['noatime','soft','nfsvers=3'], export_options: ['async,insecure,no_subtree_check,no_acl,no_root_squash']
	# config.vm.synced_folder "#{SHARED_FOLDER}","/home/vagrant/linuxdistro",type: "nfs", mount_options: ["dmode=777", "fmode=666"]
	config.vm.synced_folder "#{SHARED_FOLDER}","/home/vagrant/linuxdistro",type: "nfs", linux__nfs_options: ["no_root_squash"]
	

	# config.nfs.map_uid = Process.uid
	# config.nfs.map_gid = Process.gid

	config.vm.provision "requirements", type: 'shell', privileged: true, inline:
		"sed -i 's|deb http://us.archive.ubuntu.com/ubuntu/|deb mirror://mirrors.ubuntu.com/mirrors.txt|g' /etc/apt/sources.list
		dpkg --add-architecture i386
		apt-get -q update
		echo 'Purging unecessary packages'
		apt-get purge -q -y snapd lxcfs lxd ubuntu-core-launcher snap-confine
		echo 'Installing required packages'
		apt-get -q -y install build-essential libncurses5-dev \
			git bzr cvs mercurial subversion libc6:i386 unzip bc
		echo 'Cleaning up'
		apt-get -q -y autoremove
		apt-get -q -y clean
		update-locale LC_ALL=C"

	#obs: There's a run: 'never' tag
	config.vm.provision "buildroot", type: 'shell', privileged: false, inline:
		"echo 'Configuring the environment'
		cd linuxdistro
		if [ ! -d '/home/vagrant/linuxdistro/buildroot' ]; then echo 'Downloading and extracting buildroot #{RELEASE}' && \
		wget https://buildroot.uclibc.org/downloads/buildroot-#{RELEASE}.tar.gz && \
		tar -zxvf buildroot-#{RELEASE}.tar.gz && \
		rm buildroot-#{RELEASE}.tar.gz && \
		mv buildroot-#{RELEASE}/ buildroot && \
		mkdir buildroot/dl && \
		sed -e '2d' buildroot/.gitignore; \
		else  echo 'buildroot already downloaded'; fi
		echo 'Provision completed'"


end





