# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: Felipe Pfeifer Rubin
# Contact: felipe.rubin@acad.pucrs.br
# About: A Vagrant file for OS Labs - PUCRS 2018/2
# Configuration from: http://www.inf.pucrs.br/~emoreno/
#
#
#
#
#


# Buildroot version to use
RELEASE = '2017.11.2'
VM_MEMORY = 2048
VM_CORES = 2
SHARED_FOLDER = File.dirname(__FILE__)+"/../sharedfolder/"
Vagrant.configure("2") do |config|

	config.vm.box = 'bento/ubuntu-16.04'

	config.vm.box = 'bento/ubuntu-16.04'

	config.vm.provider :vmware_fusion do |v, override|
		v.vmx['memsize'] = VM_MEMORY
		v.vmx['numvcpus'] = VM_CORES
	end

	config.vm.provider :virtualbox do |v, override|
		v.memory = VM_MEMORY
		v.cpus = VM_CORES

		required_plugins = %w( vagrant-vbguest )
		required_plugins.each do |plugin|
		  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
		end
	end


	config.vm.provider :parallels do |v, override|
		v.memory = VM_MEMORY
		v.cpus = VM_CORES  
		
		required_plugins = %w( vagrant-parallels )
		required_plugins.each do |plugin|
			system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
		end
		override.vm.box = "parallels/ubuntu-16.04"
	end

	config.vm.provision 'shell' do |s|
		s.inline = 'echo Setting up machine name'

		config.vm.provider :vmware_fusion do |v, override|
			v.vmx['displayname'] = "Buildroot #{RELEASE}"
		end

		config.vm.provider :virtualbox do |v, override|
			v.name = "Buildroot #{RELEASE}"
		end
		config.vm.provider :parallels do |v, override|
			v.name = "Buildroot #{RELEASE}"
		end
	end

	# config.vm.synced_folder "#{SHARED_FOLDER}",'/home/vagrant/linuxdistro'
	config.vm.synced_folder "#{SHARED_FOLDER}",'/home/vagrant/linuxdistro'

	config.vm.provision 'shell', privileged: true, inline:
		"sed -i 's|deb http://us.archive.ubuntu.com/ubuntu/|deb mirror://mirrors.ubuntu.com/mirrors.txt|g' /etc/apt/sources.list
		dpkg --add-architecture i386
		apt-get -q update
		echo 'Purging unecessary packages'
		apt-get purge -q -y snapd lxcfs lxd ubuntu-core-launcher snap-confine
		echo 'Installing required packages'
		apt-get -q -y install build-essential libncurses5-dev \
			git bzr cvs mercurial subversion libc6:i386 unzip bc
		echo 'Cleaning up'
		apt-get -q -y autoremove
		apt-get -q -y clean
		update-locale LC_ALL=C"

	config.vm.provision 'shell', privileged: false, inline:
		"echo 'Creating environment'
		cd linuxdistro
		echo 'Downloading and extracting buildroot #{RELEASE}'
		wget https://buildroot.uclibc.org/downloads/buildroot-#{RELEASE}.tar.gz
		tar -zxvf buildroot-#{RELEASE}.tar.gz
		rm buildroot-#{RELEASE}.tar.gz
		mv buildroot-#{RELEASE}/ buildroot/
		mkdir buildroot/dl
		echo 'Provision completed'"
end













